pipeline:
  lint:
    image: dart:2.18.1
    commands:
      - dart pub get
      - dart analyze --fatal-infos --fatal-warnings
  test:
    image: dart:2.18.1
    commands:
      - dart pub get
      - dart test
  notify:
    image: git.polynom.me/papatutuwawa/woodpecker-xmpp
    settings:
      xmpp_is_muc: 1
      xmpp_tls: 1
      xmpp_recipient: moxxy-build@muc.moxxy.org
      xmpp_alias: 2Bot
    secrets: [ xmpp_jid, xmpp_password, xmpp_server ]
    when:
      status:
        - failure
