name: omemo_dart
description: An XMPP library independent OMEMO library
version: 0.1.0

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  cryptography:
  pinenacl:

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
