name: omemo_dart
description: An XMPP library independent OMEMO library
version: 0.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'


dependencies:
  cryptography: ^2.0.5
  pinenacl: ^0.5.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
