name: omemo_dart
description: An XMPP library independent OMEMO library
version: 0.3.1
homepage: https://github.com/PapaTutuWawa/omemo_dart
publish_to: https://git.polynom.me/api/packages/PapaTutuWawa/pub

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  cryptography: ^2.0.5
  hex: ^0.2.0
  logging: ^1.0.2
  meta: ^1.7.0
  pinenacl: ^0.5.1
  synchronized: ^3.0.0+2

dev_dependencies:
  lints: ^2.0.0
  protobuf: ^2.1.0
  protoc_plugin: ^20.0.1
  test: ^1.21.0
  very_good_analysis: ^3.0.1
